import Head from "next/head";
import Image from "next/image";
import CryptoTracker from "./CryptoTracker";
import Logo from '../images/translogo.png';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen flex justify-center items-center bg-[#111] text-[#c3f53c]">
         <div className="flex flex-col justify-center items-center">
           <img src='https://media.discordapp.net/attachments/1023253482058285126/1026494783516061697/20221003_193314_0000.png' alt="" className="w-96 h-96"/>
           <h1 className="text-2xl">Tradify</h1>
         </div>
      </div>
    </div>
  );
}
